-- Tabla: Unidades de medida
CREATE TABLE IF NOT EXISTS measurement_units (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    value INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Alter: Productos
ALTER TABLE products ADD COLUMN quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN unit_id INTEGER;
